// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// CaseController is an autogenerated mock type for the CaseController type
type CaseController struct {
	mock.Mock
}

// DeleteCase provides a mock function with given fields: c
func (_m *CaseController) DeleteCase(c *gin.Context) {
	_m.Called(c)
}

// GetCase provides a mock function with given fields: c
func (_m *CaseController) GetCase(c *gin.Context) {
	_m.Called(c)
}

// GetCases provides a mock function with given fields: c
func (_m *CaseController) GetCases(c *gin.Context) {
	_m.Called(c)
}

// PostCase provides a mock function with given fields: c
func (_m *CaseController) PostCase(c *gin.Context) {
	_m.Called(c)
}

// PutCase provides a mock function with given fields: c
func (_m *CaseController) PutCase(c *gin.Context) {
	_m.Called(c)
}
